name: cicd
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Verify there are no stupid typos in the repository
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Typos check should be pinned to the very specific version
      # to prevent sudden dictionary updates from making the CI fail
      - uses: crate-ci/typos@v1.6.0

  mdbook-build-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    # Validating the links to external websites may fail due to rate limiting or
    # sudden external resource outage, so we cannot rely on this check
    continue-on-error: ${{ matrix.follow-web-links }}

    strategy:
      matrix:
        follow-web-links:
          - true
          - false
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install-mdbook.sh

      - run: echo 'follow-web-links = ${{ matrix.follow-web-links }}' >> book.toml
      - run: mdbook build

      # Push the built book to `gh-pages` branch
      - if: ${{ !matrix.follow-web-links }}
        run: |
          git worktree add gh-pages gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages

          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force
